export const type_mapping = new Map()
type_mapping.set('arrow_function', 'ArrowFunctionExpression')
type_mapping.set('statement_block', 'BlockStatement')
type_mapping.set('statement_identifier', 'Identifier')
type_mapping.set('binary_expression', 'LogicalExpression')
type_mapping.set('number', 'Literal')
type_mapping.set('regex', 'Literal')

export const field_map = new Map()
field_map.set('new_expression', 'expression')
field_map.set('call_expression', 'expression')
field_map.set('constructor', 'callee')
field_map.set('function', 'callee')
