name: Check and build

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v4

            - name: Install Nix
              uses: cachix/install-nix-action@v27
            - uses: DeterminateSystems/magic-nix-cache-action@v7
              with: 
                use-flakehub: false
                diff-store: true
                diagnostic-endpoint: ""

            - name: Nix flake check
              run: nix flake check
