name: Check and build

on:
    pull_request:
    push:
        branches:
            - main
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v4

            - name: Install Nix
              uses: cachix/install-nix-action@v26

            - name: Nix flake check
              run: nix flake check
